# Generated by Django 2.2.7 on 2019-11-15 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0002_card_personalcard_republiccard'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField()),
                ('forniture', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='cards.Card', verbose_name='card')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='person.Person', verbose_name='person')),
            ],
        ),
    ]
