# Generated by Django 2.2.7 on 2019-11-15 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('republic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('first_name', models.CharField(max_length=60, verbose_name='First Name')),
                ('surname', models.CharField(max_length=60, verbose_name='Surname')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='Phonenumber')),
                ('date_of_birth', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Birth date')),
                ('gender', models.IntegerField(blank=True, choices=[(1, 'Masculino'), (2, 'Feminino')], default=1, verbose_name='Gender')),
                ('nationality', models.CharField(blank=True, default='Brasil', max_length=30, verbose_name='Nacionality')),
                ('facebook', models.CharField(blank=True, max_length=30, verbose_name='Facebook')),
                ('google', models.CharField(blank=True, max_length=30, verbose_name='Google +')),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='CostumUser')),
                ('Republic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='republic.Republic', verbose_name='republic')),
            ],
        ),
    ]
