# Generated by Django 2.2.6 on 2019-11-12 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Birth date'),
        ),
        migrations.AddField(
            model_name='person',
            name='facebook',
            field=models.CharField(blank=True, max_length=30, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Masculino'), (2, 'Feminino')], default=1, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='person',
            name='google',
            field=models.CharField(blank=True, max_length=30, verbose_name='Google +'),
        ),
        migrations.AddField(
            model_name='person',
            name='nationality',
            field=models.CharField(blank=True, default='Brasil', max_length=30, verbose_name='Nacionality'),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=11, verbose_name='Phonenumber'),
        ),
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='CostumUser'),
        ),
    ]
