# Generated by Django 2.2.6 on 2019-10-23 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('location', models.CharField(max_length=200)),
                ('expenses', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
            ],
        ),
    ]
