# Generated by Django 2.2.6 on 2019-10-25 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('republic', '0001_initial'),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('location', models.CharField(max_length=200)),
                ('expenses', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonalCard',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cards.Card')),
            ],
            bases=('cards.card',),
        ),
        migrations.CreateModel(
            name='RepublicCard',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cards.Card')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='republiccards', to='republic.Republic', verbose_name='republic')),
            ],
            bases=('cards.card',),
        ),
    ]
