# Generated by Django 2.2.6 on 2019-10-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepublicCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('location', models.CharField(max_length=200)),
                ('expenses', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
