# Generated by Django 2.2.6 on 2019-10-24 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0002_personalcard_republiccard'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalcard',
            name='ownerPersonal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards_republiccard', to='person.Person', verbose_name='person'),
        ),
    ]
