# Generated by Django 2.2.6 on 2019-10-24 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_republiccard'),
    ]

    operations = [
    ]
