# Generated by Django 2.2.6 on 2019-10-25 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_personalcard_republiccard'),
    ]

    operations = [
    ]
