# Generated by Django 2.2.6 on 2019-10-25 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20191025_0023'),
    ]

    operations = [
    ]
