# Generated by Django 2.2.6 on 2019-11-12 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_personalcard_owner'),
    ]

    operations = [
    ]
