# Generated by Django 2.2.6 on 2019-10-25 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_personalcard_ownerpersonal'),
    ]

    operations = [
    ]
