# Generated by Django 2.2.6 on 2019-10-24 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_personalcard_ownerpersonal'),
    ]

    operations = [
    ]
