# Generated by Django 2.2.6 on 2019-11-12 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20191112_1455'),
    ]

    operations = [
    ]
