# Generated by Django 2.2.6 on 2019-10-24 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20191024_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalcard',
            name='ownerPersonal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person', verbose_name='person'),
        ),
        migrations.AlterField(
            model_name='republiccard',
            name='ownerRepublic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='republic.Republic', verbose_name='republic'),
        ),
    ]
