# Generated by Django 2.2.6 on 2019-10-25 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20191025_0000'),
    ]

    operations = [
    ]
