# Generated by Django 2.2.6 on 2019-10-24 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20191024_2328'),
    ]

    operations = [
    ]
